// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2fEFqf1pJKoIGVynz4Rbzc04OKxjPXqE',
    appId: '1:414971735571:android:dbac300b76a72cbf1499e6',
    messagingSenderId: '414971735571',
    projectId: 'emotion-rec-mobile',
    storageBucket: 'emotion-rec-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9rr41_xRwQMV0illKt_CSe0Iz4vPPQ9k',
    appId: '1:414971735571:ios:f11162a3853934d21499e6',
    messagingSenderId: '414971735571',
    projectId: 'emotion-rec-mobile',
    storageBucket: 'emotion-rec-mobile.firebasestorage.app',
    androidClientId: '414971735571-159neoquekocfkkh0s6bkrus6qg9jf79.apps.googleusercontent.com',
    iosClientId: '414971735571-0ioanpm28avar7kf38gqmmt0mc5brqtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionmobilversion',
  );
}
